#define PORT 6575
#define ALLOWED_NO_OF_BOOKINGS 50
#define TICKET_BOOKING 1

#define ADMIN 2
#define AGENT 3
#define CUSTOMER 1


#define ADD_TRAIN 1
#define DELETE_TRAIN 2
#define MODIFY_TRAIN 3
#define SEARCH_USER 4
#define ADD_USER 5
#define DELETE_USER 6
#define MODIFY_USER 7
#define SEARCH_TRAIN 8
#define SIGNOUT 9

#define SUCCESS 1
#define FAILED 0
#define ALREADYEXIST 2
#define DOESNOTEXIST 3
#define INSUF_SEATS 4
#define CANCELLED_BK 5

#define CANCELLED 2
#define CONFIRMED 1

#define BOOK_TICKET 1
#define VIEW_BOOKING 2
#define UPDATE_BOOKING 3
#define CANCEL_BOOKING 4
#define CHECK_AVAILABILITY


